apiVersion: apps/v1
kind: Deployment
metadata:
  name: googleclothes-deployment
  labels:
    app: googleclothes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googleclothes
  template:
    metadata:
      labels:
        app: googleclothes
    spec:
      containers:
      - name: googleclothes
        image: 602643042505.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googleclothes:e74bf14be9f24e2704c1c7c25ab5ecffb57664af
        ports:
        - containerPort: 80
