apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 602643042505.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlemusic:e74bf14be9f24e2704c1c7c25ab5ecffb57664af
        ports:
        - containerPort: 80
