apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 204790445608.dkr.ecr.ap-south-1.amazonaws.com/shopping-site-googlemusic:bed720322d2f92711ed6d7dc71c25225df22d4f5
        ports:
        - containerPort: 80
