apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlemusic-deployment
  labels:
    app: googlemusic
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlemusic
  template:
    metadata:
      labels:
        app: googlemusic
    spec:
      containers:
      - name: googlemusic
        image: 204790445608.dkr.ecr.ap-south-1.amazonaws.com/shopping-site-googlemusic:0a4c602006c7390e69edce186f02e6e361e2ef64
        ports:
        - containerPort: 80
