apiVersion: apps/v1
kind: Deployment
metadata:
  name: googlepay-deployment
  labels:
    app: googlepay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: googlepay
  template:
    metadata:
      labels:
        app: googlepay
    spec:
      containers:
      - name: googlepay
        image: 602643042505.dkr.ecr.us-east-1.amazonaws.com/shopping-site-googlepay:e74bf14be9f24e2704c1c7c25ab5ecffb57664af
        ports:
        - containerPort: 80
