apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 204790445608.dkr.ecr.ap-south-1.amazonaws.com/shopping-site-phones:5e540c668d1e1580ba3caf710c2ab8d673bf88ea
        ports:
        - containerPort: 80
