apiVersion: apps/v1
kind: Deployment
metadata:
  name: phones-deployment
  labels:
    app: phones
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phones
  template:
    metadata:
      labels:
        app: phones
    spec:
      containers:
      - name: phones
        image: 070593202443.dkr.ecr.us-east-1.amazonaws.com/shopping-site-phones:2f90fadb590dfc71bff39471a16cb021e032dafe
        ports:
        - containerPort: 80
